runtime: python311 # or another supported version

env_variables:
  GAE_VERSION: 1-0-0
  PID: 1011666293677

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
  login: admin